
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.CertificationCategoryScalarFieldEnum = {
  id: 'id',
  category: 'category',
  track: 'track',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CertificationEnrollmentsScalarFieldEnum = {
  id: 'id',
  topcoderCertificationId: 'topcoderCertificationId',
  userId: 'userId',
  userHandle: 'userHandle',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  completedAt: 'completedAt',
  userName: 'userName',
  completionUuid: 'completionUuid',
  completionEventId: 'completionEventId'
};

exports.Prisma.CertificationResourceScalarFieldEnum = {
  id: 'id',
  resourceProviderId: 'resourceProviderId',
  resourceableId: 'resourceableId',
  resourceableType: 'resourceableType',
  displayOrder: 'displayOrder',
  completionOrder: 'completionOrder',
  resourceDescription: 'resourceDescription',
  resourceTitle: 'resourceTitle',
  topcoderCertificationId: 'topcoderCertificationId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CertificationResourceProgressesScalarFieldEnum = {
  id: 'id',
  certificationEnrollmentId: 'certificationEnrollmentId',
  certificationResourceId: 'certificationResourceId',
  status: 'status',
  resourceProgressId: 'resourceProgressId',
  resourceProgressType: 'resourceProgressType',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DataVersionScalarFieldEnum = {
  version: 'version'
};

exports.Prisma.FccCertificationProgressesScalarFieldEnum = {
  id: 'id',
  fccCertificationId: 'fccCertificationId',
  certProgressDynamoUuid: 'certProgressDynamoUuid',
  fccCourseId: 'fccCourseId',
  userId: 'userId',
  certification: 'certification',
  certificationId: 'certificationId',
  certificationTitle: 'certificationTitle',
  certificationTrackType: 'certificationTrackType',
  certType: 'certType',
  courseKey: 'courseKey',
  status: 'status',
  startDate: 'startDate',
  lastInteractionDate: 'lastInteractionDate',
  completedDate: 'completedDate',
  academicHonestyPolicyAcceptedAt: 'academicHonestyPolicyAcceptedAt',
  currentLesson: 'currentLesson',
  certificationImageUrl: 'certificationImageUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  email: 'email',
  completionEventId: 'completionEventId'
};

exports.Prisma.FccCompletedLessonsScalarFieldEnum = {
  id: 'id',
  fccModuleProgressId: 'fccModuleProgressId',
  dashedName: 'dashedName',
  completedDate: 'completedDate'
};

exports.Prisma.FccCoursesScalarFieldEnum = {
  id: 'id',
  fccCourseUuid: 'fccCourseUuid',
  providerId: 'providerId',
  key: 'key',
  title: 'title',
  certificationId: 'certificationId',
  estimatedCompletionTimeValue: 'estimatedCompletionTimeValue',
  estimatedCompletionTimeUnits: 'estimatedCompletionTimeUnits',
  introCopy: 'introCopy',
  keyPoints: 'keyPoints',
  completionSuggestions: 'completionSuggestions',
  note: 'note',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  learnerLevel: 'learnerLevel',
  skills: 'skills'
};

exports.Prisma.FccLessonsScalarFieldEnum = {
  id: 'id',
  fccModuleId: 'fccModuleId',
  title: 'title',
  dashedName: 'dashedName',
  isAssessment: 'isAssessment',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FccModuleProgressesScalarFieldEnum = {
  id: 'id',
  module: 'module',
  moduleStatus: 'moduleStatus',
  lessonCount: 'lessonCount',
  isAssessment: 'isAssessment',
  startDate: 'startDate',
  lastInteractionDate: 'lastInteractionDate',
  completedDate: 'completedDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  fccCertificationProgressId: 'fccCertificationProgressId'
};

exports.Prisma.FccModulesScalarFieldEnum = {
  id: 'id',
  fccCourseId: 'fccCourseId',
  key: 'key',
  name: 'name',
  dashedName: 'dashedName',
  estimatedCompletionTimeValue: 'estimatedCompletionTimeValue',
  estimatedCompletionTimeUnits: 'estimatedCompletionTimeUnits',
  introCopy: 'introCopy',
  isAssessment: 'isAssessment',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  order: 'order'
};

exports.Prisma.FreeCodeCampCertificationScalarFieldEnum = {
  id: 'id',
  fccId: 'fccId',
  key: 'key',
  providerCertificationId: 'providerCertificationId',
  title: 'title',
  certification: 'certification',
  completionHours: 'completionHours',
  state: 'state',
  certificationCategoryId: 'certificationCategoryId',
  certType: 'certType',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  learnerLevel: 'learnerLevel',
  description: 'description',
  resourceProviderId: 'resourceProviderId'
};

exports.Prisma.ResourceProviderScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  attributionStatement: 'attributionStatement',
  url: 'url',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SequelizeMetaScalarFieldEnum = {
  name: 'name'
};

exports.Prisma.TopcoderCertificationScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  status: 'status',
  sequentialCourses: 'sequentialCourses',
  learnerLevel: 'learnerLevel',
  version: 'version',
  certificationCategoryId: 'certificationCategoryId',
  stripeProductId: 'stripeProductId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  learningOutcomes: 'learningOutcomes',
  prerequisites: 'prerequisites',
  dashedName: 'dashedName',
  introText: 'introText',
  learnedOutcomes: 'learnedOutcomes',
  skills: 'skills'
};

exports.Prisma.TopcoderUdemyCourseScalarFieldEnum = {
  id: 'id',
  title: 'title',
  status: 'status',
  updatedAt: 'updatedAt',
  removedAt: 'removedAt'
};

exports.Prisma.UdemyCourseScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  headline: 'headline',
  url: 'url',
  categories: 'categories',
  topics: 'topics',
  promo_video_url: 'promo_video_url',
  instructors: 'instructors',
  requirements: 'requirements',
  what_you_will_learn: 'what_you_will_learn',
  level: 'level',
  images: 'images',
  locale: 'locale',
  primary_category: 'primary_category',
  primary_subcategory: 'primary_subcategory',
  estimated_content_length: 'estimated_content_length',
  estimated_content_length_video: 'estimated_content_length_video',
  num_lectures: 'num_lectures',
  num_videos: 'num_videos',
  last_update_date: 'last_update_date',
  data_version: 'data_version'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.enum_CertificationEnrollments_status = exports.$Enums.enum_CertificationEnrollments_status = {
  enrolled: 'enrolled',
  disenrolled: 'disenrolled',
  completed: 'completed'
};

exports.ResourceableType = exports.$Enums.ResourceableType = {
  FreeCodeCampCertification: 'FreeCodeCampCertification',
  TopcoderUdemyCourse: 'TopcoderUdemyCourse'
};

exports.enum_CertificationResourceProgresses_status = exports.$Enums.enum_CertificationResourceProgresses_status = {
  not_started: 'not_started',
  in_progress: 'in_progress',
  completed: 'completed'
};

exports.enum_FccCertificationProgresses_status = exports.$Enums.enum_FccCertificationProgresses_status = {
  in_progress: 'in_progress',
  completed: 'completed',
  not_started: 'not_started'
};

exports.enum_FccCourses_learnerLevel = exports.$Enums.enum_FccCourses_learnerLevel = {
  Beginner: 'Beginner',
  Intermediate: 'Intermediate',
  Expert: 'Expert',
  All_Levels: 'All_Levels'
};

exports.enum_FccModuleProgresses_moduleStatus = exports.$Enums.enum_FccModuleProgresses_moduleStatus = {
  not_started: 'not_started',
  in_progress: 'in_progress',
  completed: 'completed'
};

exports.CertificationStatus = exports.$Enums.CertificationStatus = {
  active: 'active',
  inactive: 'inactive',
  deprecated: 'deprecated',
  coming_soon: 'coming_soon'
};

exports.FccCertificationType = exports.$Enums.FccCertificationType = {
  certification: 'certification',
  course_completion: 'course_completion'
};

exports.enum_FreeCodeCampCertification_learnerLevel = exports.$Enums.enum_FreeCodeCampCertification_learnerLevel = {
  Beginner: 'Beginner',
  Intermediate: 'Intermediate',
  Expert: 'Expert',
  All_Levels: 'All_Levels'
};

exports.LearnerLevel = exports.$Enums.LearnerLevel = {
  Beginner: 'Beginner',
  Intermediate: 'Intermediate',
  Expert: 'Expert',
  All_Levels: 'All_Levels'
};

exports.CourseStatus = exports.$Enums.CourseStatus = {
  available: 'available',
  coming_soon: 'coming_soon',
  not_available: 'not_available',
  removed: 'removed'
};

exports.Prisma.ModelName = {
  CertificationCategory: 'CertificationCategory',
  CertificationEnrollments: 'CertificationEnrollments',
  CertificationResource: 'CertificationResource',
  CertificationResourceProgresses: 'CertificationResourceProgresses',
  DataVersion: 'DataVersion',
  FccCertificationProgresses: 'FccCertificationProgresses',
  FccCompletedLessons: 'FccCompletedLessons',
  FccCourses: 'FccCourses',
  FccLessons: 'FccLessons',
  FccModuleProgresses: 'FccModuleProgresses',
  FccModules: 'FccModules',
  FreeCodeCampCertification: 'FreeCodeCampCertification',
  ResourceProvider: 'ResourceProvider',
  SequelizeMeta: 'SequelizeMeta',
  TopcoderCertification: 'TopcoderCertification',
  TopcoderUdemyCourse: 'TopcoderUdemyCourse',
  UdemyCourse: 'UdemyCourse'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
