Description: TCA - Generate and serve certificate images and SSR
Parameters:
    TCAGenerateCertificateQueueName:
        Type: String
        Description: TCA Generate Certificate Queue Name
        Default: tca-generate-certificate"
Resources:
    TCAGenerateCertificateQueue:
        Type: AWS::SQS::Queue
        DeletionPolicy: Delete
        Properties:
            QueueName:
                Ref: TCAGenerateCertificateQueueName
