Description: TCA - Generate and serve certificate images and SSR

Parameters:

    TCAGenerateCertificateQueueName:
        Type: String
        Description: TCA Generate Certificate Queue Name

    TCACertificateImageStoreName:
        Type: String
        Description: TCA Generate Certificate Image Store Name

    TCACertificateImageStoreDomain:
        Type: String
        Description: TCA Generate Certificate Image Store Domain

    TCACertificateImageStoreAlias:
        Type: String
        Description: TCA Generate Certificate Image Store Alias

    TCACertificateImageStoreCdnCertArn:
        Type: String
        Description: TCA Generate Certificate Distribution Arn

    TCACertificateImageStoreAliasHostedZoneId:
        Type: String
        Description: TCA Generate Certificate Image Store Alias Hosted Zone Id

Resources:

    TCAGenerateCertificateQueue:
        Type: AWS::SQS::Queue
        DeletionPolicy: Delete
        Properties:
            QueueName:
                Ref: TCAGenerateCertificateQueueName

    TCACertificateImageStore:
        Type: AWS::S3::Bucket
        DeletionPolicy: Delete
        Properties:
            AccessControl: PublicRead
            BucketName:
                Ref: TCACertificateImageStoreName

    TCACertificateImageStoreBucketPolicy:
        Type: 'AWS::S3::BucketPolicy'
        Properties:
            Bucket: !Ref TCACertificateImageStore
            PolicyDocument:
                Id: TCACertificateImageStoreBucketPolicy
                Version: 2012-10-17
                Statement:
                    -   Sid: PublicReadForGetBucketObjects
                        Effect: Allow
                        Principal: '*'
                        Action: 's3:GetObject'
                        Resource: !Join 
                        - ''
                        -   - 'arn:aws:s3:::'
                            - !Ref TCACertificateImageStore
                            - /*

    TCAGenerateCertificateCdn:
        Type: AWS::CloudFront::Distribution
        Properties: 
            DistributionConfig: 
                Enabled: true
                Aliases: 
                    -   Ref: TCACertificateImageStoreAlias
                Origins:
                    -   Id: 
                            Ref: TCACertificateImageStoreDomain
                        DomainName: 
                            Ref: TCACertificateImageStoreDomain
                        S3OriginConfig:
                            OriginAccessIdentity: ""
                DefaultCacheBehavior:
                    TargetOriginId: 
                        Ref: TCACertificateImageStoreDomain
                    ViewerProtocolPolicy: redirect-to-https
                    ForwardedValues:
                        QueryString: false
                        Cookies:
                            Forward: none
                ViewerCertificate: 
                    AcmCertificateArn: 
                        Ref: TCACertificateImageStoreCdnCertArn
                    MinimumProtocolVersion: TLSv1.2_2018
                    SslSupportMethod: sni-only

    TCAGenerateCertificateRoute:
        Type: AWS::Route53::RecordSet
        Properties:
            HostedZoneId: 
                Ref: TCACertificateImageStoreAliasHostedZoneId
            Name:
                Ref: TCACertificateImageStoreAlias
            Type: A
            AliasTarget: 
                # hard-coded zone id for all cloudfront routes
                # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
                HostedZoneId: Z2FDTNDATAQYW2 
                DNSName: !GetAtt TCAGenerateCertificateCdn.DomainName
