const urlExists = require('url-exists')

const imageGenerator = require('../generate-certificate-image/GenerateCertificateImageService')
const paramHelper = require('../env-param-helper')

const certProgressStore = require('./CertificationProgressStore')
const userStore = require('./UserStore')

// init the env vars on load
const {
    imageDomain,
} = paramHelper.initializeEnvironmentParams(
    [
        'CERT_IMAGE_DOMAIN',
    ],
    [
        'imageDomain'
    ])

/**
 * Generates a cert image.
 * 
 * @param {string} certProgress The Certification Progress record for the
 * image we need to generate
 * 
 * NOTE: If the we can't find a handle linked to the user's ID, we can't create
 * an image.
 */
async function generateCertificateImageAsync(certProgress) {

    // if we can't find a handle, there's nothing to do
    const handle = await userStore.getHandleFromId(certProgress.userId, imageDomain)
    if (!handle) {
        return
    }

    // generate the images asynchronously in the bg
    console.debug('generating for', handle)
    imageGenerator.generateCertificateImage(
        handle,
        certProgress.certification,
        certProgress.provider,
        // WARNING: This URL format is generated by the frontend, and there's no good way to share it btwn
        // apps, so just hard-coding here.
        `https://platform-ui.${imageDomain}/learn/${certProgress.provider}/${certProgress.certification}/${handle}/certificate`,
        '[class^=Certificate_wrap]',
        certProgress,
    )
}

/**
 * Callback for handling whether or not a Cert Image actually exists at its URL
 * 
 * @param {string} certProgress The Certification Progress record for the
 * image for which we are checking its cert image URL
 */
function handleImageUrlExistsRequest(certProgress) {

    return (err, certificateExists) => {

        // if we got an error, we have a prob
        if (!!err) {
            console.error(`Checking existence of ${certProgress.certificationImageUrl} caused ${err}`)
            return
        }

        // if the image exists, don't do anything
        if (certificateExists) {
            console.log('Exists:', certProgress.certificationImageUrl)
            return
        }

        console.log(`${certProgress.certificationImageUrl} does NOT exist. Generating...`)
        generateCertificateImageAsync(certProgress)
    }
}

/**
 * Processes all the completed certs that have a cert image URL assigned but the image
 * doesn't actually exist
 * 
 * @param {Array<Object>} completedCertifications The list of Certification Progress 
 * records that have been completed
 */
async function processCompletedWithMissingImage(completedCertifications) {

    // filter records to only completed courses that DID have an image generated
    const completedWithImage = completedCertifications
        .filter(certProgress => !!certProgress.certificationImageUrl)
    console.log(`Found ${completedWithImage.length} completed courses that DID have an image generated.`)

    // check that the image exists and create those that don't
    completedWithImage
        .forEach(certProgress => urlExists(certProgress.certificationImageUrl, handleImageUrlExistsRequest(certProgress)))
}

/**
 * Processes all the completed certs that do not have a cert image URL assigned
 * 
 * @param {Array<Object>} completedCertifications The list of Certification Progress 
 * records that have been completed
 */
async function processCompletedWithNoImageUrl(completedCertifications) {

    // filter records to only completed courses that don't
    // have an image url assigned
    const noImageExists = completedCertifications
        .filter(certProgress => !certProgress.certificationImageUrl)

    console.log(`Found ${noImageExists.length} completed courses that never had an image generated.`)

    // generate the missing images
    noImageExists
        .forEach(certProgress => generateCertificateImageAsync(certProgress))
}

/**
 * Generates All the Certifications that don't exist
 */
async function regenerateImagesAsync() {

    const completedCertifications = await certProgressStore.getAllCompleted()

    processCompletedWithNoImageUrl(completedCertifications)

    processCompletedWithMissingImage(completedCertifications)
}

// run the regeneration on load
regenerateImagesAsync()
    .then(() => console.debug('Finished the sync portion of the script with the async bg logs to follow...'))
