/**
 * A simple Express JS server to receive Stripe webhooks locally. Use this in 
 * combination with the CLI `stripe listen` command and `stripe trigger` to 
 * generate webhooks locally.
 * 
 * NOTE: Webhooks generated by the Stripe CLI will also be received by the 
 * endpoint in AWS API Gateway. 
 */

const express = require('express');
const app = express();
const webhookHandler = require('./webhook_handler');

app.post('/webhook', express.raw({ type: 'application/json' }), (request, response) => {
    webhookHandler.handle(request)
        .then((handlerResponse) => {
            response.status(handlerResponse.statusCode).send(handlerResponse.body);
        })
});

app.listen(4242, () => console.log('Running on port 4242'));